version: '3.2'

services:
  ubuntu:
    build: ubuntu
    container_name: ubuntu
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www:/var/www
      - ./ubuntu/sites-config:/etc/apache2/docker-sites-config
    hostname: webserver.loc
    environment:
      - TZ=UTC
    networks:
      - webserver
  mysql8:
    image: ubuntu/mysql:8.0-22.04_beta
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql8:/var/lib/mysql:rw
    environment:
      - TZ=UTC
      - MYSQL_PORT=3306
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
      - DEBIAN_FRONTEND=noninteractive
    hostname:
      mysql.db
    networks:
      - webserver
  redis:
    image: redis
    container_name: redis
    hostname:
      redis.db
    networks:
      - webserver
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./clickhouse:/var/lib/clickhouse/:rw
    environment:
      - TZ=UTC
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    hostname:
      clickhouse.db
    networks:
      - webserver

networks:
  webserver:
    driver: bridge